{
 "title": "DOMjudge",
 "tags": [ "DOMjudge" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "contest",
    "query": {
     "query": "label_values(domjudge_teams,contest)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Submissions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domjudge_submissions_total{contest=~'$contest'}",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "Unverified Submissions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domjudge_submissions_unverified{contest=~'$contest'}",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "Ignored Submissions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domjudge_submissions_ignored{contest=~'$contest'}",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "Correct Submissions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domjudge_submissions_correct{contest=~'$contest'}",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "Total teams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domjudge_teams{contest=~'$contest'}",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "Logged in teams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domjudge_teams_logged_in{contest=~'$contest'}",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "Submitted teams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domjudge_teams_submitted{contest=~'$contest'}",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "Correct teams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domjudge_teams_correct{contest=~'$contest'}",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "Submission Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "domjudge_submissions_total{contest=~'$contest'}",
     "legendFormat": "{{contest}} total"
    },
    {
     "expr": "domjudge_submissions_correct{contest=~'$contest'}",
     "legendFormat": "{{contest}} correct"
    }
   ]
  },
  {
   "title": "Submission Statistics Delta",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(domjudge_submissions_total{contest=~'$contest'}[1m])",
     "legendFormat": "{{contest}} total"
    },
    {
     "expr": "delta(domjudge_submissions_correct{contest=~'$contest'}[1m])",
     "legendFormat": "{{contest}} correct"
    }
   ]
  },
  {
   "title": "Judging Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(domjudge_submissions_queued{contest=~'$contest'}) by (contest)",
     "legendFormat": "{{contest}}"
    }
   ]
  }
 ]
}